BEGIN TRANSACTION;
DROP TABLE IF EXISTS "test";
CREATE TABLE IF NOT EXISTS "test" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL,
	"period"	INTEGER NOT NULL,
	"dt"	REAL NOT NULL,
	"total_iteration"	INTEGER NOT NULL,
	"period_center"	INTEGER NOT NULL,
	"enable_mutation"	INTEGER NOT NULL
);
DROP TABLE IF EXISTS "test_result";
CREATE TABLE IF NOT EXISTS "test_result" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"id_test"	INTEGER NOT NULL,
	"iteration"	INTEGER NOT NULL,
	"dna"	TEXT NOT NULL,
	"tangentPlane"	TEXT NOT NULL,
	"center"	INTEGER NOT NULL
);
COMMIT;
